// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXaPGxHyKIn2uERlcMfyn6t-ae39isY7U',
    appId: '1:983886489871:web:28c5114cf88bd60b17367a',
    messagingSenderId: '983886489871',
    projectId: 'fir-login-app-497a3',
    authDomain: 'fir-login-app-497a3.firebaseapp.com',
    storageBucket: 'fir-login-app-497a3.firebasestorage.app',
    measurementId: 'G-3HNT6J7LNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnaF1rQOcIXNaOZyKQmzm_D5FLkSzJYHU',
    appId: '1:983886489871:android:d96e051e0cbdfc9d17367a',
    messagingSenderId: '983886489871',
    projectId: 'fir-login-app-497a3',
    storageBucket: 'fir-login-app-497a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBLVv6eWjP5H-VwV_kfQr94qYtHmQcKtE',
    appId: '1:983886489871:ios:be46db7dfa94218717367a',
    messagingSenderId: '983886489871',
    projectId: 'fir-login-app-497a3',
    storageBucket: 'fir-login-app-497a3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBLVv6eWjP5H-VwV_kfQr94qYtHmQcKtE',
    appId: '1:983886489871:ios:be46db7dfa94218717367a',
    messagingSenderId: '983886489871',
    projectId: 'fir-login-app-497a3',
    storageBucket: 'fir-login-app-497a3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLoginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXaPGxHyKIn2uERlcMfyn6t-ae39isY7U',
    appId: '1:983886489871:web:6fb13853a420d53317367a',
    messagingSenderId: '983886489871',
    projectId: 'fir-login-app-497a3',
    authDomain: 'fir-login-app-497a3.firebaseapp.com',
    storageBucket: 'fir-login-app-497a3.firebasestorage.app',
    measurementId: 'G-BGNEG0XG12',
  );
}
